version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
    ports:
      - "8080:8080"
    depends_on:
      - dbec
  webui:
    build:
      context: .
      dockerfile: Dockerfile.webui
    ports:
      - "80:80"
    depends_on:
      - api
  dbec:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbec2
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
