apiVersion: v1
kind: Service
metadata:
  name: {{ include "database-chart.fullname" . }}
spec:
  selector:
    app: {{ include "database-chart.name" . }}
  ports:
    - name: postgres
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
