replicaCount: 1
image:
  repository: jetigenov2455/api
  tag: ${{ github.sha }}
  pullPolicy: IfNotPresent
aws:
  accessKeyId: AWS_ACCESS_KEY_ID
  secretAccessKey: AWS_SECRET_ACCESS_KEY
service:
  type: NodePort
  port: 8080
