apiVersion: v1
kind: Service
metadata:
  name: {{ include "webui-chart.fullname" . }}
spec:
  selector:
    app: {{ include "webui-chart.name" . }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 80
  type: {{ .Values.service.type }}
