name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push API image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.api
        push: true
        tags: jetigenov2455/api:${{ github.sha }}

    - name: Build and push Webui image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.webui
        push: true
        tags: jetigenov2455/webui:${{ github.sha }}

    - name: Build and push DB image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.db
        push: true
        tags: jetigenov2455/postgres:${{ github.sha }}

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --vm-driver=docker

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Deploy the Helm chart
      run: |
        helm install api ./api-chart --set image.tag=${{ github.sha }}
        helm install webui ./webui-chart --set image.tag=${{ github.sha }}
        helm install db ./database-chart --set image.tag=${{ github.sha }}
